[build]
  publish = "dist"
  command = "npm run build"
# [context.production.environment]
#   LOGIN_URL = "https://auth.vystem.us/vystem/authorize"
#   API_URL = "https://api.vystem.us"
#   API_PORT = '443'
#   API_SSL = 'true'

# [context.staging.environment]
#   LOGIN_URL = "https://auth.vystem.us/vystem/authorize"
#   API_URL = "https://staging-api.vystem.us"
#   API_PORT = '443'
#   API_SSL = 'true'

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-key header rules are expressed with multi-line strings.
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

    # Basic-Auth allows you to password protect your whole site.
    # This feature may not be available on all plans.
    # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"